# Suggested data paths when using GPT-NeoX locally
{
  # "data_path": "data/wiki_ja",
  # "data_path": "data/wiki_ja/wiki_ja_text_document",

  # or for weighted datasets:
  "train-data-paths": ["data/wiki_ja_novelAI_bin/wiki_ja_text_document", "data/oscar_ja_novelAI_bin/oscar_ja_text_document","data/wiki_en_novelAI_bin/wiki_en_text_document" ,"data/aozora_ja_novelAI_bin/aozora_ja_text_document"],
  "test-data-paths": ["data/wiki_ja_novelAI_bin/wiki_ja_text_document", "data/oscar_ja_novelAI_bin/oscar_ja_text_document","data/wiki_en_novelAI_bin/wiki_en_text_document" ,"data/aozora_ja_novelAI_bin/aozora_ja_text_document"],
  "valid-data-paths": ["data/wiki_ja_novelAI_bin/wiki_ja_text_document", "data/oscar_ja_novelAI_bin/oscar_ja_text_document","data/wiki_en_novelAI_bin/wiki_en_text_document" ,"data/aozora_ja_novelAI_bin/aozora_ja_text_document"],
  "train-data-weights": [0.9, 0.9, 0.9, 0.9],
  "test-data-weights": [0.1, 0.1, 0.1, 0.1],
  "valid-data-weights": [0.1, 0.1, 0.1, 0.1],

  # If weight_by_num_documents is True, Builds dataset weights from a multinomial distribution over groups of data according to the number of documents in each group.
  # WARNING: setting this to True will override any user provided weights
  # "weight_by_num_documents": false,
  # "weighted_sampler_alpha": 0.3,
  
  "vocab_file": "./novelAI/tokenizer.model",  

  #"save": "checkpoints",
  # "load": "checkpoints",
  "save": "/content/drive/MyDrive/pre_trained/49M/checkpoints",
  "load": "/content/drive/MyDrive/pre_trained/49M/checkpoints",

  "checkpoint_validation_with_forward_pass": False,

  ## logging
  # "log_dir": "logs",
  "log_dir": "/content/drive/MyDrive/pre_trained/49M/logs", 

  # "tensorboard_dir": "tensorboard",
  "tensorboard_dir": "/content/drive/MyDrive/pre_trained/49M/tensorboard", 
  # "log_dir": "logs",
  "use_wandb": False
}
